### ISSUE TITLE
New release after classmapper fix?

### ISSUE THREAD

**Issue by CThuleHansen** [nickbattle/vdmj#39]
Hi Nick,

Is it possible to create a new release and push it to artifactory such that we can propagate the fix through to FMI-VDM-Model and maestro2?

(link for reference: https://github.com/nickbattle/vdmj/pull/38)

**Comment by nickbattle** [comment]
Happy to try, but I've never done this before. I was going to try:
```
mvn -Dmaven.repo.local=repository release:clean
mvn -Dmaven.repo.local=repository release:prepare -DreleaseVersion=4.3.0 -DdevelopmentVersion=4.3.1-SNAPSHOT
mvn -Dmaven.repo.local=repository release:perform
```
But that failed at the prepare stage:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.293 s
[INFO] Finished at: 2020-11-05T08:58:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project vdm: Missing required setting: scm connection or developerConnection must be specified. -> [Help 1]
```
The POM currently has:
```
	<distributionManagement>
	    <repository>
	        <id>vdmj.overture.au.dk-central</id>
	        <name>overture.au.dk-releases</name>
	        <url>https://overture.au.dk/artifactory/vdmj</url>
	    </repository>
	    <snapshotRepository>
	        <id>vdmj.overture.au.dk-snapshots</id>
	        <name>overture.au.dk-snapshots</name>
	        <url>https://overture.au.dk/artifactory/vdmj</url>
	    </snapshotRepository>
	</distributionManagement>
```
Do you know what's wrong?

**Comment by CThuleHansen** [comment]
the maven release plugin:
1. Changes the POM version to what you set in `-DreleaseVersion` (4.3.0 in this case)
2. Creates a tag
3. Pushes pom commit and tag
4. Changes the POM version version to what you set in -DdevelopmentVersion (4.3.1-SNAPSHOT)
5. Pushes.

So for this reason, it requires some sort of scm connection on where to do this. 
See i.e. here for overture
https://github.com/overturetool/overture/blob/development/pom.xml#L405-L410

or here for maestro: (pretty much the same)
https://github.com/INTO-CPS-Association/maestro/blob/development/pom.xml#L377-L385

Has Kenneth created a user for you on artifactory and given your the information on how to set up settings.xml?

**Comment by nickbattle** [comment]
I managed to sort out what was missing - some POM sections - and I've tried some dry runs to check everything works before I end up committing the changes (or it does that for me). But I think it's close. I had to re-organise the POMs a bit to be in the structure it expects, but it wasn't hard.

No, I don't remember Kenneth telling me the login details. Can you check with him?

**Comment by CThuleHansen** [comment]
PAssed in private.
There is already a release 4.3.0 in artifactory, probably the one that kenneth did. 
Maybe bump the version number?

**Comment by nickbattle** [comment]
OK, so this is getting closer (though it is a painful incremental process). Now the clean and prepare work, but the final perform is failing when it tries to push to the repo in Aarhus. I have the settings.xml in place with the user/password you sent. The error is:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project vdmj: Failed to deploy artifacts: Could not transfer artifact com.fujitsu:vdmj:jar:4.3.0 from/to vdmj.overture.au.dk-central (https://overture.au.dk/artifactory/vdmj): Transfer failed for https://overture.au.dk/artifactory/vdmj/com/fujitsu/vdmj/4.3.0/vdmj-4.3.0.jar 401 Unauthorized -> [Help 1]
```
I can see that there already is a 4.3.0 in the repo, though "unauthorized" sounds like a credential problem. I could try bumping the version number, but I'd rather know what's going on before making arbitrary changes. Can that existing 4.3.0 be removed?

**Comment by nickbattle** [comment]
Incidentally, I can login to ArtiFactory at Aarhus directly using the same credentials, so I'm pretty sure it is an *authorization* issue (I can't overwrite artifacts) rather than an *authentication* issue.  If we could remove the manually added entries, I should be able to re-build them "officially".

**Comment by CThuleHansen** [comment]
I think you are correct.
The issue with removing them manually is that FMI-VDM-Model already depends on it, so it will break.
Alternatively, you could try a snapshot version? THere can be multiple snapshots versions added.

**Comment by nickbattle** [comment]
So I tried a deploy of 4.3.1-SNAPSHOT, using `mvn deploy` but it gave me a similar 401 unauthorized error when it tried to update ArtiFactory:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project vdmj: Failed to deploy artifacts: Could not transfer artifact com.fujitsu:vdmj:jar:4.3.1-20201106.150242-1 from/to vdmj.overture.au.dk-snapshots (https://overture.au.dk/artifactory/vdmj): Transfer failed for https://overture.au.dk/artifactory/vdmj/com/fujitsu/vdmj/4.3.1-SNAPSHOT/vdmj-4.3.1-20201106.150242-1.jar 401 Unauthorized -> [Help 1]
```
I see that the URL to the snapshots repository in distributionManagement is the same as the one for releases. Is that wrong, perhaps? `https://overture.au.dk/artifactory/vdmj` Though it was trying to create a new snapshot subfolder, so that should have been OK?

**Comment by CThuleHansen** [comment]
I will try Monday, can you push the snapshot version one to a branch?

**Comment by nickbattle** [comment]
I've moved the master and highprecision branches both over to be 4.3.0-SNAPSHOT (in anticipation of a release). They're both pushed (ie. GitHub is up to date).

**Comment by CThuleHansen** [comment]
Great Will try monday!

**Comment by CThuleHansen** [comment]
Hi Nick,
I just had luck with pushing a snapshot version ussing `mvn -B -X deploy` (Not performing an actual release)
# The main issue - versions
It tried to deploy, which was not possible.
```
Failed to deploy artifacts: Could not transfer artifact com.fujitsu:annotations:jar:1.0.0 from/to vdmj.overture.au.dk-central (https://overture.au.dk/artifactory/vdmj): Authorization failed for https://overture.au.dk/artifactory/vdmj/com/fujitsu/annotations/1.0.0/annotations-1.0.0.jar 403 Forbidden -> [Help 1]
```
So I looked in the annotations plugin, and it contains 
```
<version>1.0.0</version>
```
Which is already uploaded to artifactory.
This was the case for other modules as well.

I fixed it by setting this property in the root pom.xml:
```		
<maven.deploy.skip>true</maven.deploy.skip>
```
And in the vdmj/pom.xml:
```
        <maven.deploy.skip>false</maven.deploy.skip>
```
And then the deploy worked - [link](https://overture.au.dk/artifactory/webapp/#/artifacts/browse/tree/General/vdmj/com/fujitsu/vdmj/4.3.0-SNAPSHOT/vdmj-4.3.0-20201109.075943-2.jar) 

**Comments**
Having the modules at separate versions can present a challenge. I.e. `annotations` depends on `vdmj`, so not updating the version of `annotations` when updating its dependency to `vdmj` will mean that your local `annotations` project will depend on a newer `vdmj` version, but the pushed annotations project will not. 

This will also cause an issue in FMI-VDM model, where the dependency to `annotations` would still be `1.0.0`, which would use `vdmj 4.3.0`, but the dependency to `vdmj` would be updated to `4.3.0-SNAPSHOT`. 
See https://github.com/INTO-CPS-Association/FMI-VDM-Model/blob/master/fmi2/fmi2vdm/pom.xml#L24-L33

What we do is to have a version at the root pom, which all the submodules inherit. All the submodules are then at the same version number. We do this, because we are publishing a coherent set of modules every time. One module does not depend on a legacy version of another module

# Other issue - SCM settings
This will probably be an issue with the real release. In the SCM settings there was not an url for the actual repo, rather there was the url to nickbattle profile. 
Remember, it pushes to the repo.
Yours:
```
<scm>
		<connection>scm:git:https://github.com/nickbattle</connection>
		<developerConnection>scm:git:https://github.com/nickbattle</developerConnection>
	</scm>
```
My fork for comparison:
```
	<scm>
		<url>git@github.com:cthulehansen/vdmj</url>
		<connection>scm:git:git//github.com/cthulehansen/vdmj</connection>
		<developerConnection>scm:git:git@github.com:cthulehansen/vdmj</developerConnection>
	</scm>

```

Here is the diff from my fork to your fork: 
https://github.com/nickbattle/vdmj/pull/40

**Comment by nickbattle** [comment]
So firstly, thanks for looking at this. I know it's annoying to fix other people's stuff, especially when there's a lot of history there and things aren't perhaps done as you might expect!

I see your point about mixing releases and snapshots. In the past, all of the parts of the "suite" were released independently (in fact the release process was pretty informal), so it didn't really matter. But in a formalised world with repositories it makes more sense to consistently version the whole suite.

I will try to move *everything* to be 4.3.0, fixing the inter-module dependencies, and then re-release/deploy 4.3.0 to ArtiFactory. Then we can probably remove the "delete" permission again - safer that way.

Would that give you what you need?

**Comment by CThuleHansen** [comment]
> So firstly, thanks for looking at this. I know it's annoying to fix other people's stuff, especially when there's a lot of history there and things aren't perhaps done as you might expect! 

It is useful for me to have to go these things myself, as Kenneth has usually taken care of it from AU side. I am learning as well!

> I see your point about mixing releases and snapshots. In the past, all of the parts of the "suite" were released independently (in fact the release process was pretty informal), so it didn't really matter. But in a formalised world with repositories it makes more sense to consistently version the whole suite.

All code-bases have their own story. I think the maven practise is to separate different "clusters" of projects by more parent POMs. But with the ease of access to github repositories and organizations, this is probably shifting...

> I will try to move everything to be 4.3.0, fixing the inter-module dependencies, and then re-release/deploy 4.3.0 to ArtiFactory. Then we can probably remove the "delete" permission again - safer that way.

Sounds reasonable. Let me know how it goes!

> Would that give you what you need?

It would elevate us to the next step, a new release of FMI-VDM model with updated vdmj modules. I think this is still necessary, even though the versions remain the same.

**Comment by nickbattle** [comment]
Right!  That worked beautifully :-)  So now there is a new 4.3.0 release and 4.3.0-P release of every artifact in the VDMJ suite uploaded to ArtiFactory.  The snapshots you did earlier are still there, of course. Should they be removed, to avoid confusion?

**Comment by nickbattle** [comment]
There also some old crud in there because I changed the groupId to be consistent across the suite too. Might cause confusion if that's left lying around (though harmless, as long as people choose the right artifact to depend on).

**Comment by CThuleHansen** [comment]
I think a new release of FMI-VDM model is necessary

**Comment by CThuleHansen** [comment]
I think the ${revision} replacement did not kick in

**Comment by nickbattle** [comment]
Yeah I was just looking at that. I tried to use ${revision} to set the suite version number in one place, and the suite builds fine with that, but it seems that when you use the POMs from the repo to build something else, it isn't happy. Will try some experiments...

**Comment by nickbattle** [comment]
Hmmm. So it looks like if you're depending on (say) VDMJ 4.3.0, it can't work out that the POM's use of `${revision}` comes from the parent. It's the same if you go into a submodule and use Maven there: since it hasn't seen the parent POM to start with, it can't see the `${revision}`. So I think I'll have to change the POM versions to be explicit everywhere - or at least in the parent clauses, so that it can find the parent POM and hence the revision...

**Comment by nickbattle** [comment]
OK, I just deployed an updated VDMJ (alone) with explicit parent version numbers, and now the FMI-VDM-Model builds OK, though there is something wrong with the assembly process. I'll deploy the same fix for the rest of VDMJ first, so that at least ArtiFactory is consistent.

**Comment by nickbattle** [comment]
FMI-VDM-Model (development branch) now fixed and pushed, though the assembly is still giving a couple of warnings, that seem to be related to the old `${revision}` setting. Perhaps the POMs are cached somewhere, though I can't see them locally. If you "mvn clean install" for FMI-VDM-Model, do you see these warnings?
```
[INFO] --- maven-assembly-plugin:3.1.1:single (default) @ fmi2vdm ---
[INFO] Reading assembly descriptor: src/assembly/assembly.xml
[WARNING] Failed to build parent project for com.fujitsu:vdmj:jar:4.3.0
[WARNING] Failed to build parent project for com.fujitsu:annotations:jar:4.3.0
[INFO] Building zip: /home/nick/Digital Twins/INTO-CPS-Association/FMI-VDM-Model/fmi2/fmi2vdm/target/vdmcheck-1.0.1-SNAPSHOT-201109-distribution.zip
```
The ZIP file looks OK though...

**Comment by CThuleHansen** [comment]
I get: 
`[WARNING] Failed to build parent project for com.fujitsu:vdmj:jar:4.3.0`
and 
`[WARNING] Failed to build parent project for com.fujitsu:vdmj:jar:4.3.0-P`

**Comment by nickbattle** [comment]
Mmm... same. If you use the -X you can see that it's moaning about `${revision}` again, but the parent clauses are all fixed now. Unless it's getting an older pom from one of the repositories?? If you deleted your .m2, then it must be getting it from elsewhere, so maybe it will sync up in a while?

**Comment by CThuleHansen** [comment]
It looks like the one of artifactory still has a weird revision from the top level pom
https://overture.au.dk/artifactory/webapp/#/artifacts/browse/tree/PomView/vdmj/com/fujitsu/vdmj-suite/4.3.0/vdmj-suite-4.3.0.pom
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>com.fujitsu</groupId>
	<artifactId>vdmj-suite</artifactId>
	<name>VDMJ Suite</name>
	<packaging>pom</packaging>
	<version>${revision}</version>	<!-- This version is used for all modules -->
	
	<properties>
	    <maven.build.timestamp.format>yyMMdd</maven.build.timestamp.format>
	    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	    <revision>4.3.0</revision>	<!-- CHANGE VERSION HERE, AND MODULE'S PARENT POMs -->
	</properties>

	<!-- sub modules -->
	<modules>
		<module>Annotations</module>
		<module>Annotations2</module>
		<module>FJ-VDMJ4</module>
		<module>FJ-VDMJC4</module>
		<module>FJ-VDMJUnit4</module>
		<module>LSP</module>
	</modules>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.5.1</version>
				<configuration>
					<goals>deploy</goals>
				</configuration>
...
```

**Comment by nickbattle** [comment]
Yeah, but I thought that was OK - though there is very little point I suppose. Darn it. I suppose I can try getting rid of the revision variable all together (from version fields - it's useful for dependencies still).

**Comment by nickbattle** [comment]
OK, just deployed a new version without ANY revisions, and the warning goes away! :-)

**Comment by CThuleHansen** [comment]
https://maven.apache.org/maven-release/maven-release-plugin/examples/prepare-release.html

Gives you details of how the release plug-in works. It can update all of the versions

**Comment by nickbattle** [comment]
Yes, I saw that when I was trying to use the release plugin originally (which would have worked, if I had had permissions). I'm actually a bit nervous of it doing lots of thing for me(!), especially if it's pushing commits and creating tags; if anything goes wrong, it can be as much work to sort out the mess as it would be to do the job manually with deploy.

I need to keep working on VDMJ now (for the LSP guys), so I will create a new snapshot, probably 4.4.0-SNAPSHOT as LSP support is more than a "bugfix". At some point I will release that too, and we can decide whether to bump FMI-VDM-Model forward, or whether it's fine on 4.3.0.

**Comment by CThuleHansen** [comment]
Sure thing 🙂 lets close this then?!

**Comment by nickbattle** [comment]
All done!
