### ISSUE TITLE
Cannot Generate Proof Obligations for 'ext' statements

### ISSUE THREAD

**Issue by adamdb5** [nickbattle/vdmj#47]
When trying to generate proof obligations for operations using the `ext` statement, the following exception is raised:
`java.lang.Exception: No mapping for class com.fujitsu.vdmj.tc.statements.TCExternalClause in tc-po.mappings`

An example VDM-SL model that generates this exception is as follows:
```
module TestPO
definitions
state State of
	myNat: nat
end;

operations
	changeMyNat() == myNat := 1
	ext wr myNat;
end TestPO
```
Version:
`VDMJ version = 4.4.2 build 210211`

**Comment by nickbattle** [comment]
Thanks for reporting this. I happened to notice this too a few days ago too. It has been fixed in the latest VDMJ snapshot. Do you need a fixed jar quickly?

**Comment by adamdb5** [comment]
If you have one available then that would be great!

**Comment by nickbattle** [comment]
Give one of these a try:

https://github.com/nickbattle/vdmj/releases/download/4.4.3-1/vdmj-4.4.3-SNAPSHOT.jar
https://github.com/nickbattle/vdmj/releases/download/4.4.3-1/vdmj-4.4.3-P-SNAPSHOT.jar

Note that some of VDMJ's properties have changed names in this release. Take a look at the properties file below for the new names, if you need any of these:

https://github.com/nickbattle/vdmj/releases/download/4.4.3-1/vdmj.properties

**Comment by nickbattle** [comment]
OK, that's fine... I'll close this issue now.
