### ISSUE TITLE
Malformed URI in LSP response

### ISSUE THREAD

**Issue by donbex** [nickbattle/vdmj#54]
When using the LSP with neovim, after initialization the server returns
```
16:40:25.059: <<< LSP { "jsonrpc" : "2.0", "method" : "textDocument/publishDiagnostics", "params" : { "uri" : "file:/Users/***/code/vdm/AccountSysSL/AccountSys.vdmsl", "diagnostics" : [  ] } }
```
The URI in this response is malformed (it should start with `file:///` instead of `file:/`) and it causes neovim to throw an error:
```
Error executing vim.schedule lua callback: ...l/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/uri.lua:116: URI must contain a scheme: file:/Users/alessandro.pezzoni/code/vdm/AccountSysSL/AccountSys.vdmsl
```
This was tested on macOS Catalina 10.15.7, but I can also test on Arch Linux if needed.

**Comment by donbex** [comment]
Looking more closely at this, it would appear that the [specification for file URI schemes](https://datatracker.ietf.org/doc/html/rfc8089#section-2) also allows the `file:/` form for local files, so I should probably just raise this as a bug with neovim.

**Comment by nickbattle** [comment]
It's interesting that neovim explicitly looks for a particular format of URI. I _think_ the URIs sent are legal, according to the RFC:
```
Appendix B.  Example URIs

   The syntax in Section 2 is intended to support file URIs that take
   the following forms:

   Local files:

   o  A traditional file URI for a local file with an empty authority.
      This is the most common format in use today.  For example:

      *  "file:///path/to/file"

   o  The minimal representation of a local file with no authority field
      and an absolute path that begins with a slash "/".  For example:

      *  "file:/path/to/file"
```
So LSP is using the last case there, and this is produced by the Java URI class' toString method, which is presumably valid.

But this is academic if neovim won't accept it!

I can extract the various toString cases and use a method to produce a different format, but I would obviously have to make sure that other platforms are happy with this as well before committing. If there are differences, I will have to produce some sort of "file URI format" configuration setting to allow different platforms to select the one they want.

**Comment by nickbattle** [comment]
We crossed in the post there! It would be interesting to see what neovim have to say, but I suspect it will be quicker to get a fix into VDMJ/LSP :-)

**Comment by donbex** [comment]
Since the `file:/` form adheres to the specification and since the fix appears much simpler on the neovim side, I think the best course of action is to try to have this fixed there, at least at first.

The team that develops neovim is very active and friendly, so I hope this will be resolved quickly enough.

**Comment by donbex** [comment]
My neovim PR has been merged, so I think we can safely close this issue now.

**Comment by nickbattle** [comment]
So how does VDMJ's LSP work with neovim now? (Just curious!)

**Comment by donbex** [comment]
> So how does VDMJ's LSP work with neovim now? (Just curious!)

Pretty well, but with a couple of caveats:

- Diagnostics work flawlessly, especially paired with [trouble.nvim](https://github.com/folke/trouble.nvim) (which provides a nice UI for listing errors across the entire project).
- Go-to-definition and completion work fine with the couple of [Overture examples](https://www.overturetool.org/download/examples/VDMSL/) I tested, but unfortunately they do nothing in my work project. This is not limited to neovim however, and it is also a problem in Overture and VSCode.
- Neovim does not support proof obligation generation and combinatorial testing out of the box. It shouldn't be too difficult to write a plugin to add those capabilities, but we don't use either at my workplace so they are low priority for me.

**Comment by nickbattle** [comment]
Thanks for that.

I'd be happy to look at your Go-to-definition issues, if it's possible to share the model that doesn't work (or to create a cut down model that illustrates the problem)? There have been a few cases where it failed in the past, but these were usually very obscure expression types - most of the time it was fine. So perhaps there is something more fundamental going on here.

You could raise a new VDMJ issue, or contact me directly (nick.battle(at)gmail.com).

**Comment by donbex** [comment]
Thanks for the offer. Unfortunately I am not allowed to share our model, so I will have to try to create a minimal (non) working example. I haven't yet been able to isolate the cause of the issue, but I suspect it is related to the fact that our specification is split across multiple sub-projects.

**Comment by nickbattle** [comment]
OK. Obviously something reproducible is easiest for me(!). But perhaps your sub-project structure is the reason. Can you clarify this? VSCode will associate one VDMJ instance with every top-level folder that contains SL/PP/RT sources. Subfolders are scanned, but have no special meaning to VDMJ. If the spec is split between two or more top-level folders, it will regard these as separate and independent specs - ie. it will not navigate between them, but it should be OK within them.

I have some SL projects with sub-folders that navigate fine.

**Comment by donbex** [comment]
So, I ran the language server through my debugger once again and it appears that the issue is indeed due to our project structure... in a silly way.

We use [our VDM Gradle plugin](https://github.com/anaplan-engineering/vdm-gradle-plugin) to manage the dependencies between those sup-projects and to "compile" them into a form that allows animation. The language server was picking up the build artifacts, causing hundreds (literally!) of type checking errors for doubly-defined modules and resulting in `LSPWorkspaceManager.checkLoadedFiles` to fail.

It would be really useful if the language server could respect a `.gitignore` if found in the workspace, or at least if it could be possible to supply ignore patterns via an option.

Interestingly, it looks like parsing errors (from the AST plugin) are reported to the LSP client, but type checking errors [are simply dumped to the log file](https://github.com/nickbattle/vdmj/blob/9ce741ce37b284984c9c6fbce190f169739897f0/lsp/src/main/java/workspace/LSPWorkspaceManager.java#L383). Would it be possible to report those as well?

**Comment by nickbattle** [comment]
Ah! Yes, I see. I had a similar problem with a pom.xml file creating packages of models by adding them to a temporary folder, which them got scanned by the Server.

You should find that the latest release (1.1.2) ignores files that are in "dotty" paths - ie. that have a path component that starts with a dot. Does that help?

The Server is set to produce syntax errors only while you type, and then do a type-check when you save. This is because of the overhead of TC for large specifications (or the inefficiency of VDMJ, if you prefer :^)). Overture is the same. Does that explain the behaviour you're seeing? Further down from the line you highlight, the tc.getErrs() are added to the message response to the client. The "syntax errors while typing" is done in a different place.

**Comment by donbex** [comment]
> You should find that the latest release (1.1.2) ignores files that are in "dotty" paths - ie. that have a path component that starts with a dot. Does that help?

Unfortunately it doesn't. In our project, the build artifacts are stored in a `build` directory in each sub-project's folder.

> The Server is set to produce syntax errors only while you type, and then do a type-check when you save. This is because of the overhead of TC for large specifications (or the inefficiency of VDMJ, if you prefer :^)). Overture is the same. Does that explain the behaviour you're seeing? Further down from the line you highlight, the tc.getErrs() are added to the message response to the client. The "syntax errors while typing" is done in a different place.

No, I meant the diagnostic notifications. The language server actually sends them out correctly for TC errors as well and neovim's log shows that they are being parsed, but for some reason the internal table that the editor uses to cache the notifications is empty. I suspect that neovim might not be coping with the sheer number of errors, since the same error is displayed correctly in a smaller example.

**Comment by nickbattle** [comment]
Hmm. OK, I don't know much about Gradle, but is it possible to set the `${project.buildDir}` to something other than the default value of "build"? Alternatively, I think your plugin says that within "build" there is a "vdm" folder. Would it be possible to change that to ".vdm"?

If these are too disruptive, I can look at honouring some sort of "ignore file". I'd rather not use ".gitignore" because there may be legitimate reasons to Git-ignore a (generated) VDM source file, but want it included in the model. There are already some properties that can be set, so I could add an "ignore list" there perhaps.

**Comment by nickbattle** [comment]
Oh! One thing you could perhaps try... you can create a file called `.vscode/ordering`. If that exists, its contents and the order they appear in is used to build the file list of the model. The idea is that it us much more efficient to type-check a model in a sensible dependency order than the default (alphabetical or just random order).

So create a file (the output of "find . -name *.vdmsl" will do) and edit it to just include the ones you want. Don't worry about the order for now, though the idea is to put least dependent things first, then files that use those definitions and so on...

If you separately would like to know the optimal* dependency ordering, let me know. There is a tool to generate it (but I can't remember how it works!!). *And it isn't perfectly optimal because it's NP-Hard, I think. But it's better than guessing!

**Comment by donbex** [comment]
> Oh! One thing you could perhaps try... you can create a file called `.vscode/ordering`. If that exists, its contents and the order they appear in is used to build the file list of the model. The idea is that it us much more efficient to type-check a model in a sensible dependency order than the default (alphabetical or just random order).

Aha, that did it! Generating a list of the specification projects in dependency ordering was pretty straightforward, since we use Gradle to manage those dependencies. The file order is still sub-optimal because it doesn't account for dependencies within a project, but I think it's good enough.

Is `.vscode/ordering` documented somewhere? If not, it definitely should be!

**Comment by nickbattle** [comment]
That's good news!

The order doesn't have to be optimal (it should work regardless of the file order), but you should find that the type checking is faster if their in natural dependency order.

This feature is experimental, and you may find problems for example when you add new files that aren't in the ordering file. It tries to alert you, but it's easy to confuse it if you're editing heavily. If enough people find it useful, we'll make it "official". If you find problems, please raise issues here and I'll try to fix them.

It *may* be possible to automatically order the modules/classes before type check one day - that is, the expense of calculating the order is compensated by the improved TC efficiency. But I'm not yet sure that the ordering algorithm is robust enough. If you want to try it, it comes as a VDMJ command line plugin called "order". So if you put the cmd-plugins jar (from the VDMJ build) on your classpath, and run VDMJ command line, you can type "order" at the command prompt, or "order <file>" to write to a file that you can subsequently rename to .vscode/ordering.

```
Type checked 7 modules in 0.301 secs. No type errors and 18 warnings
Initialized 7 modules in 0.204 secs. 
Interpreter started
> order
Generating dependency graph
Checking for cyclic dependencies
Removed 0 cycles
Ordering from startpoints: [PacemakerAAI, RateController, PacemakerAOO, PacemakerAOOR, PacemakerDOO, PacemakerDDD, PacemakerAAT]
./PacemakerAAT.vdmsl
./PacemakerDDD.vdmsl
./PacemakerDOO.vdmsl
./PacemakerAOOR.vdmsl
./PacemakerAOO.vdmsl
./RateController.vdmsl
./PacemakerAAI.vdmsl
> 
```
