### ISSUE TITLE
Scope for inline functions not correct

### ISSUE THREAD

**Issue by nickbattle** [nickbattle/vdmj#57]
Consider:
```
functions
	f: nat -> nat
	f(x) ==
		let X = 123,
			g: nat -> nat
			g(a) == a + X
		in
			g(x);

> p f(1)
Error 4034: Name 'X' not in scope in 'DEFAULT' (test.vdm) at line 6:25
```

So X is in scope for the type checking, but at runtime the closure of the inline function does not include the other variables in the same "let" context. If you move the X to an outer "let", then it's fine.

**Comment by alzibab** [comment]
f: nat -> nat
	f(x) ==
		let X = 123 in
		let
			g: nat -> nat
			g(a) == a + X
			pre
				a > X
		in
			g(x);		

> p f(1) 
Error 4034: Name 'Inline`X' not in scope

Adding a precondition to the function that uses the variable in the outer let causes an in scope error

**Comment by nickbattle** [comment]
OK, thanks. It looks like the closure for the "extra" functions has the wrong scope, even with a extra let context.
