### ISSUE TITLE
Option to output a parsed, type checked specification is present in the user guide, but unrecognized by the VDMJ tool

### ISSUE THREAD

**Issue by donbex** [nickbattle/vdmj#59]
As per title, page 5 of the [VDMJ user guide](https://github.com/nickbattle/vdmj/blob/master/vdmj/documentation/UserGuide.pdf) mentions a `-o` option to save a type checked specification to file, but this appears to be unsupported by the code.

Looking through the history of the repository I couldn't find the point in time when it was removed, although the version of VDMJ bundled with Overture does [seem to support it](https://github.com/overturetool/overture/blob/8e73876ae1e259b041db9a11afc7f8b93c385fa6/core/interpreter/src/main/java/org/overture/interpreter/VDMJ.java#L146-L159). Was the option intentionally removed and, if so, why?

**Comment by nickbattle** [comment]
Oh. I thought I'd remove this from everywhere, but you're right, it's still in the User Guide.

This option was removed from VDMJ a few years ago. It was rarely used and caused problems internally. My original thought was that it would be faster to load (Java deserialize) a type-checked tree, but in practice, it is just as fast (sometimes faster) to re-parse and check from the sources, which was quite a surprise.

Thanks for raising this though: I'll update the User Guide and check the other docs.

**Comment by nickbattle** [comment]
Document change is now pushed to development branch. This will get merged/release at the next update.

**Comment by donbex** [comment]
@nickbattle The reason I came across this is because we are using it in our Gradle plugin -- through Overture's embedded version of VDMJ -- precisely under the assumption that it would speed up re-parsing. If it does not actually provide a performance benefit, we might as well stop using it as well...

I just opened a corresponding bug report on the Overture side https://github.com/overturetool/overture/issues/785, since the behaviour there is currently broken.

**Comment by nickbattle** [comment]
If there are any Overture cases where it doesn't fail, you could try a quick performance comparison. But I found that it wasn't adding much, if anything. And when VDMJ's internals were restructured (to separate analyses without using visitors) the tree-dumping feature became awkward to maintain. Since it wasn't adding much... and no one was using it... I chopped it.

I saw the Overture bug, thanks. I'll comment on that later, so they can fix it (or remove it).
