### ISSUE TITLE
@spec(name[, weight]) annotation

### ISSUE THREAD

**Issue by leouk** [nickbattle/vdmj#61]
Nick, I wanted to suggest a new annotation. I thought to implement it in VDM_Toolkit but then wanted to share it here for thoughts/comments (or warnings!). :-) 

A while ago I tried a visitor that would go over inv/pre/post etc and attempt to calculate some things. This largely works but can get clumsy/complicated - in fairness I wasn't as familiar with the LeafVisitors then. 

For instance, the number of conjuncts (i.e. the number of proof goals that a specification part would entail) or disjuncts (i.e. the amount of assumption case analysis or consequence choices) to help identify the proof strategies needed when translating to Isabelle's proof scripts with ps2isa plugin. 

Also, if the user "knew" about the complexity of certain constructs (e.g. iota, exists1 versus >=, + etc) in expressions, a (user-defined) weight could be given to the specification. This would then again help the proof strategy inference tool to know whether to try specific assisting tools (e.g., Pressburger or linear arithmetic decision procedures for >=, +, etc.) or not, or to suggest lemmas for the "heavier" operators/parts. 

Can also be useful to "count" the specification "semantic" size (as opposed to the nominal LOC size). 

What do you think? Is this (at least in the "simple" form of counting spec parts) doable in a reasonably simple visitor or am I kidding myself over the complexity of the annotation visitation side?

Best,
Leo

**Comment by nickbattle** [comment]
It should be fairly simple to walk the tree and look for various con/disjunctions in expressions. But where would an annotation "keep" that result? Or did you mean that annotations could be used to label the spec such that another piece of analysis could use them (which would be fine)?

**Comment by nickbattle** [comment]
Maybe better to discuss this by email :-)

**Comment by nickbattle** [comment]
@leouk Did you do this as part of the VDM_Tooklit?

**Comment by leouk** [comment]
@nickbattle not yet. Guess now with my much clearer understanding of the visitors, shouldn\'t be too hard. I am focusing on the proof strategies atm, but eventually such calculations would be useful for them.

**Comment by nickbattle** [comment]
OK. But this is an issue on VDMJ :-)  Can we move it to https://github.com/leouk/VDM_Toolkit?

**Comment by leouk** [comment]
Yes.
