### ISSUE TITLE
Free variables visitor NPE on State-related clause

### ISSUE THREAD

**Issue by leouk** [nickbattle/vdmj#69]
I am getting an NPE on a TCFreeVariablesVisitor call related to state definition. 

The minimal example is 

        module M
        exports all
        definitions 
        state MSt of 
            x: nat 
        init m == m = mk_MSt(0)
        end
        end M

The module.defs has one entry as :

      TCStateDefinition
      "state MSt of
      x:nat
	      init m == (m = mk_MSt(0))
      end
      "

The module.defs.singleDefinitions has 4 entries as:

    get(0) = MSt = MSt 
    get(1) = MSt~ = MSt
    get(2) = x = nat
    get(3) = x~ = nat

This seems right to me, but the trouble is that when you say get(0).getFreeVariables(), then TCLocalDefinition have valueDefinition = null and the TCFreeVariablesVisitor on caseLocalDefinition line 186 generates the NPE, given valueDefinition is null. 

This appeared on running exu on the  VDM_Toolkit/experiments/vdm/Chesss/SL/Runner.vdmsl state definition.

L

**Comment by nickbattle** [comment]
Interesting case. A StateDefinition is using LocalDefinitions for the various named fields it produces. But these are not backed by a ValueDefinition (which is the usual case for LocalDefinitions, but not always). There is a `isValueDefinition` method on LocalDefinitions that can be used to check this before trying to use the (null) valueDefinition field, but this wasn't being checked in a couple of visitors.

I've pushed a tweak to the development branch. Can you try that?

**Comment by nickbattle** [comment]
Was this fixed, Leo?

**Comment by nickbattle** [comment]
@leouk Can we close this?

**Comment by leouk** [comment]
Guess yes.
