### ISSUE TITLE
Export the AST as JSON

### ISSUE THREAD

**Issue by TheGrandmother** [nickbattle/vdmj#70]
Howdy!
I have a potentially stupid question.

I would really like to do some experimenting with automatic code generation from VDM specifications and it would be incredibly nice to not have to write a VDM parser from scratch.

Is it possible to output the AST in JSON (or maybe some other format) from VDMJ without to much hacking or fiddling?
If not is it a feature that could conceivably be added?

**Comment by nickbattle** [comment]
Thinking about it, you might find it more useful to process a tree that has type information included. So in that case you would intercept processing after the typecheck phase, using the `CheckCompleteEvent`. But... it depends what you really want to do.

Have you seen the "VDMJ Plugin Writer's Guide"?

**Comment by TheGrandmother** [comment]
Thanks for the quick reply, I have only done some light skimming of the Plugin writers guide, but I can give it a more thorough read. I don't really know how fiddly writing such an ASTPlugin would be compared to just writing a parser from scratch.

I'm not 100% sure if I will need type information but it may very well be usable.

To give a contrived example of what I am aiming towards.:
Go from:
```vdm
types
  serverInfo ::
    loggedInUsers: set of int
    bannedUsers: set of int
    users: set of int
  inv mk_userInfo(loggedInUsers, bannedUsers, users) ==
    loggedInUsers subset users and
    bannedUsers subset users and
    bannedUsers inter loggedInUsers = {}
  ;
```
to:
```typescript
export interface ServerInfo {
  loggedInUsers: number[]
  bannedUsers: number[]
  users: number[]
}

function invServerInfo(x: ServerInfo): boolean {
  return (
    x.loggedInUsers.every(y => x.users.includes(y)) &&
    x.bannedUsers.every(y => x.users.includes(y)) &&
    x.bannedUsers.filter(y => x.loggedInUsers.includes(y)).length === 0
  )
}

export function checkServerInfo(x: any): asserts x is ServerInfo {
  checkArray(x.users, checkInt)
  checkArray(x.loggedInUsers, checkInt)
  checkArray(x.bannedUsers, checkInt)
  if (!invServerInfo(x)) {
    throw new TypeError('Invariant violation')
  }
}
```

Initially just for typescript and rust but other languages as well and eventually more than just generating type guards. It would be nice to be able to just get the AST of the vdm specification somehow. Use that to do the code generation in whatever way is best suited for each language and leave the validation and handling of the actual vdm code to some other framework, like vdmj.

**Comment by nickbattle** [comment]
The full VDM grammar can be fiddly in places. Someone was trying to write a ANTLR parser for it, but it has been a lot of effort so far.  I could perhaps sketch the outline of a JSON dumping plugin and implement a few methods (ie. a few AST node types) and then you could fill out the rest?

PS. About to go out for the day, so will be quiet!

**Comment by TheGrandmother** [comment]
>  I could perhaps sketch the outline of a JSON dumping plugin and implement a few methods (ie. a few AST node types) and then you could fill out the rest?
If you could do that I would be immensely grateful!

> PS. About to go out for the day, so will be quiet!
No worries, thanks for the quick replies! Have a lovely day :)

**Comment by nickbattle** [comment]
Okay, I've sketched a JSON dumping plugin. I'll need to explain some of it to you though - perhaps email is best?  It only deals with a small fraction of the AST nodes: so it can only cope with explicit functions, its understanding of parameter types is limited, and it can only deal with a few binary expressions. But hopefully the idea is clear enough to allow you to fill out the rest.

If you do complete this, it could be a useful plugin for various people. But I think this issue should be closed(?)

**Comment by TheGrandmother** [comment]
Thank you!! :)
I think that any small example that I can start tinkering with would be great to get things up and running and to start prototyping with.
Email works great for me you can use the one that that's on my GitHub profile!

I definitely think this issue could be closed and I'll keep you up to date on any progress that is made :)

**Comment by nickbattle** [comment]
OK, thanks. Email sent. Feel free to ask more questions by email :-)
